spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.liquibase.spring.LiquibaseAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://127.0.0.1:4200"
              - "http://127.0.0.1:4201"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://auth-service:8001
          predicates:
            - Path=/api/v1/auth/**
        - id: account-service
          uri: http://account-service:8002
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: http://transaction-service:8003
          predicates:
            - Path=/api/v1/transactions/**
        - id: ledger-service
          uri: http://ledger-service:8004
          predicates:
            - Path=/api/v1/ledger/**

eureka:
  client:
    enabled: false

server:
  port: 8000

logging:
  level:
    root: INFO
    com.digitalbanking: DEBUG
